name: Build and Test
on: [push]

jobs:
  build-and-test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
    name: ${{ matrix.os == 'ubuntu-latest' && 'linux-x86_64' || matrix.os == 'macos-13' && 'macos-x86_64' || 'windows-x86_64' }}
    env:
      ODIN_JOBS: 4
      plat: ${{ matrix.os == 'ubuntu-latest' && 'linux-x86_64' || matrix.os == 'macos-13' && 'macos-x86_64' || 'windows-x86_64' }}


    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - uses: korandoru/setup-zig@v1
        with:
          zig-version: 0.12.0
      - uses: laytan/setup-odin@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          release: dev-2024-05
      - uses: ilammy/msvc-dev-cmd@v1
        if: matrix.os == 'windows-latest'

      - uses: crazy-max/ghaction-chocolatey@v3
        name: Install wget, 7zip
        if: matrix.os == 'windows-latest'
        with:
          args: install wget 7zip

      - name: Test
        run: make test
        if: matrix.os == 'ubuntu-latest'
      - name: Test
        uses: nick-fields/retry@v3
        if: matrix.os == 'windows-latest'
        with:
          command: nmake /F Makefile.win32 test
          timeout_minutes: 2
          retry_wait_seconds: 1
          max_attempts: 5

      - name: Install dependencies
        if: matrix.os == 'ubuntu-latest'
        run: sudo apt install libglew-dev libglfw3-dev
      - name: example/olivec
        if: matrix.os == 'ubuntu-latest'
        run: make example/olivec
      - name: example/olivec
        if: matrix.os == 'windows-latest'
        run: nmake /F Makefile.win32 example/olivec
      - name: example/glew
        if: matrix.os == 'ubuntu-latest'
        run: make example/glew
      - name: example/glew
        if: matrix.os == 'windows-latest'
        run: nmake /F Makefile.win32 example/glew

      - name: Build runic release
        run: make
        if: matrix.os == 'ubuntu-latest'
      - name: Build runic release
        run: .\build.cmd
        if: matrix.os == 'windows-latest'

      - uses: actions/upload-artifact@v4
        if: matrix.os != 'windows-latest'
        with:
          name: runic-${{ env.plat }}
          path: ${{ github.workspace }}/build/runic
          if-no-files-found: warn
          overwrite: true
          compression-level: 0
      - uses: actions/upload-artifact@v4
        if: matrix.os == 'windows-latest'
        with:
          name: runic-${{ env.plat }}
          path: ${{ github.workspace }}/build/runic.exe
          if-no-files-found: warn
          overwrite: true
          compression-level: 0

  create-release:
    runs-on: ubuntu-latest
    needs: build-and-test
    if: startsWith(github.ref, 'refs/tags/')
    permissions:
      contents: write
    steps:
      - uses: actions/download-artifact@v4
        with:
          merge-multiple: true
          path: artifacts
      - name: List all artifacts
        run: ls -la --color=always artifacts
      - uses: ncipollo/release-action@v1
        with:
          artifacts: 'artifacts/*'
          body: |
            Automatically generated by Github Actions Run ${{ github.run_id }}
          generateReleaseNotes: true
          makeLatest: true